image: ubuntu:22.04

build_and_trace:
  stage: test
  before_script:
    - apt-get update && apt-get install -y build-essential cmake gcc-arm-none-eabi
  script:
    - mkdir -p firmware/build/gcc/output
    - mkdir -p build
    - cd build
    - cmake ..
    - cmake --build .
